# Generated by Django 4.2.2 on 2023-07-02 13:51

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyText', wagtail.fields.RichTextField()),
            ],
        ),
    ]
